config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
    }

  namespace :admin do
    resources :search, only: :index
    resources :users do
      member do
        get :link_telegram_url
      end
    end
    resources :assets
    resources :tags, only: [:index, :update, :destroy]
    resources :checkouts
    resources :checkins
    resources :events
    resources :locations

    root to: 'users#index'
  end

  authenticated :user do
    root 'dashboards#index', as: 'dashboards'
  end
  root to: redirect('/users/sign_in')

  get 'tags/search'

  get 'barcodes/start_scanner/:token', to: 'barcodes#start_scanner', as: 'start_barcode_scanner'
  get 'barcodes/send_telegram_link', to: 'barcodes#send_telegram_link'
  get 'barcodes/scanner'

  post 'webhooks/telegram/:token', to: 'webhooks#telegram', as: 'telegram_webhook'

  resources :assets, only: [:index] do
    collection do
      post 'search'
      post 'global_search'
    end
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!

    include Admin::VerifyAdmin
    include Administrate::Punditize

    helper_method :filter_form_attributes

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end

    def filter_form_attributes(attributes)
      attributes
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  protect_from_forgery
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  after_action :verify_authorized, unless: :devise_controller?, except: :index
  after_action :verify_policy_scoped, only: :index

  private

  def user_not_authorized
    flash[:alert] = 'You are not authorized to perform this action.'
    sign_out(current_user)
    redirect_to(new_user_session_url)
  end

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/application/_form.html.erb
<%#
# Form Partial

This partial is rendered on a resource's `new` and `edit` pages,
and renders all form fields for a resource's editable attributes.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for :head do %>
  <!-- Don't cache forms because selectize inputs will be duplicated -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<%= form_for([namespace, page.resource], html: { class: "form" }) do |f| %>
  <% if page.resource.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= t(
          "administrate.form.errors",
          pluralized_errors: pluralize(page.resource.errors.count, t("administrate.form.error")),
          resource_name: display_resource_name(page.resource_name).singularize
        ) %>
      </h2>

      <ul>
        <% page.resource.errors.full_messages.each do |message| %>
          <li class="flash-error"><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% filter_form_attributes(page.attributes).each do |attribute| -%>
    <div class="field-unit field-unit--<%= attribute.html_class %> field-unit--<%= requireness(attribute) %>">
      <%= render_field attribute, f: f %>
    </div>
  <% end -%>

  <div class="form-actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/application/_header.html.erb
<% content_for :javascript do %>
  <%= render 'barcodes/global_vars' %>

  <script type="text/javascript">
    $(function() {
      const $dropdownToggle = $('.barcode-scanner-btn');
      const $dropdownContent = $('.dropdown-content');

      const handleClickOutsideDropdown = (event) => {
        if (!$(event.target).closest('.dropdown-button').length) {
          $dropdownContent.css('display', 'none');
          $(document).off('click', handleClickOutsideDropdown);
        }
      };

      $dropdownToggle.on('click', () => {
        $dropdownContent.css('display', 'flex');
        $(document).off('click', handleClickOutsideDropdown);
        $(document).on('click', handleClickOutsideDropdown);
      });

      $('#open-on-device-btn').on('click', e => {
        e.preventDefault();
        window.open(
          '<%= barcodes_scanner_path %>',
          'newwindow',
          'width=400,height=600'
        );
      });

      $('#send-telegram-btn').on('click', e => {
        e.preventDefault();
        $.get('<%= barcodes_send_telegram_link_path %>').catch(err =>
          console.error('Error generating start_scanner URL:\n', err)
        );
      });

      $('#connect-telegram-btn').on('click', e => {
        e.preventDefault();
        window.location.href = '<%= edit_admin_user_path(current_user) %>';
      });
    });
  </script>
<% end %>

<header class="admin-app-header">
  <div class="admin-app-header__content">
    <h1>NCAS Asset Management</h1>

    <%= link_to('Sign Out', destroy_user_session_path, method: 'DELETE', class: 'right-aligned') %>

    <div class="dropdown-wrapper">
      <button class="button button--alt dropdown-button barcode-scanner-btn">
        <%= image_pack_tag 'media/images/barcode-scanner.svg' %>
        <span class="label-text">Barcode Scanner</span>
      </button>

      <div class="dropdown-content">
        <ul>
          <li id="open-on-device-btn">
            <%= image_pack_tag 'media/images/external-link.svg', class: 'dropdown-icon' %>
            <%= link_to('Open on this device', barcodes_scanner_path) %>
          </li>

          <% if current_user.telegram.present? %>
            <li id="send-telegram-btn">
              <%= image_pack_tag 'media/images/telegram-logo.svg', class: 'dropdown-icon' %>
              <a href="#">Send a link to my Telegram</a>
            </li>
          <% else %>
            <li id="connect-telegram-btn">
              <%= image_pack_tag 'media/images/telegram-logo.svg', class: 'telegram-logo' %>
              <span>
                <%= link_to('Connect your Telegram', edit_admin_user_path(current_user)) %>
                and I can send a link to your phone!
              </span>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/admin/application/_javascript.html.erb
<%#
# Javascript Partial

This partial imports the necessary javascript on each page.
By default, it includes the application JS,
but each page can define additional JS sources
by providing a `content_for(:javascript)` block.

Administrate::Engine.javascripts.each do |js_path|
 <= echo javascript_include_tag js_path
<% end %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });

    // Destroy all selectize instances before turbolinks caches a page
    // TODO - breaks restoration of selectize fields after failed form submit
    $(document).on('turbolinks:before-cache', function() {
      $('[data-selectize]').each(function() { this.selectize.destroy() });
    });
  <% end %>
<% end %>

app/views/admin/application/_navigation.html.erb
<%#
# Navigation

This partial is used to display the navigation in Administrate.
By default, the navigation contains navigation links
for all resources in the admin dashboard,
as defined by the routes in the `admin/` namespace
%>

<nav class="navigation" role="navigation">
  <%= link_to(admin_search_index_path, class: "button button--alt button--nav search-btn") do %>
    <svg class="search__eyeglass-icon" role="img">
      <title>
        Search
      </title>
      <use xlink:href="#icon-eyeglass"></use>
    </svg>
    Search
  <% end %>

  <% Administrate::Namespace.new(namespace).resources_with_index_route.each do |resource| %>
    <%# Search is shown as a button above ^ %>
    <%= next if resource == 'search' %>

    <%= link_to(
      display_resource_name(resource),
      resource_index_route(resource),
      class: "navigation__link navigation__link--#{nav_link_state(resource)}"
    ) if valid_action?(:index, resource) && show_action?(:index, model_from_resource(resource)) %>
  <% end %>
</nav>