config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'users/omniauth_callbacks',
    }

  namespace :admin do
    resources :search, only: :index
    resources :users do
      member do
        get :link_telegram_url
      end
    end
    resources :assets
    resources :tags, only: [:index, :update, :destroy]
    resources :checkouts
    resources :checkins
    resources :events
    resources :locations

    root to: 'users#index'
  end

  authenticated :user do
    root 'dashboards#index', as: 'dashboards'
  end
  root to: redirect('/users/sign_in')

  get 'tags/search'

  get 'barcodes/start_scanner/:token', to: 'barcodes#start_scanner', as: 'start_barcode_scanner'
  get 'barcodes/send_telegram_link', to: 'barcodes#send_telegram_link'
  get 'barcodes/scanner'

  post 'webhooks/telegram/:token', to: 'webhooks#telegram', as: 'telegram_webhook'

  resources :assets, only: [:index] do
    collection do
      post 'search'
      post 'global_search'
    end
  end
end

app/views/fields/telegram_username_field/_form.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    $(function() {
      const getBotStartUrl = '<%= link_telegram_url_admin_user_path(current_user) %>';
      $('.start-bot-link').click(e => {
        e.preventDefault();
        e.stopPropagation();
        $.get(getBotStartUrl)
          .then(url => window.open(url, '_blank'))
          .catch(err => console.error('Error getting bot start URL:\n', err));
      });
    });
  </script>
<% end %>

<div class="field-unit__label" style="margin-bottom: auto;">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <% if current_user.telegram_chat_id.present? %>
    Linked: <%= link_to(
      field.to_s,
      "tg://resolve?domain=#{field.to_s[1..]}",
      class: 'fucking-blue-link',
    ) %>
    <br />
    <p class="info-text">
      To unlink, use "Stop and block bot" in Telegram
    </p>
  <% else %>
    Start our bot
    <a class="start-bot-link" href="#">using this link</a>
    to link your Telegram
  <% end %>
</div>

app/views/fields/telegram_username_field/_index.html.erb
<% if field.to_s.present? -%>
  <%= link_to(
    field.to_s,
    "tg://resolve?domain=#{field.to_s[1..]}",
    class: 'fucking-blue-link',
  ) %>
<% end %>

app/views/fields/telegram_username_field/_show.html.erb
<% if field.to_s.present? %>
  <%= link_to(
    field.to_s,
    "tg://resolve?domain=#{field.to_s[1..]}",
    class: 'fucking-blue-link',
  ) %>
<% end %>